<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Caravel.Clarion/Caravel.Clarion.csproj" Condition="'$(CaravelPackageVersion)' == ''" />
    <PackageReference Include="Clinimatix.Caravel.Clarion" VersionOverride="$(CaravelPackageVersion)" Condition="'$(CaravelPackageVersion)' != ''" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
