<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Caravel.AspNetCore/Caravel.AspNetCore.csproj" Condition="'$(CaravelPackageVersion)' == ''" />
    <PackageReference Include="Clinimatix.Caravel.AspNetCore" VersionOverride="$(CaravelPackageVersion)" Condition="'$(CaravelPackageVersion)' != ''" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
  </ItemGroup>
</Project>
