<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Clinimatix.Caravel.Auth</PackageId>
    <Description>Native ASP.NET Core Identity conventions for the Clinimatix Caravel framework.</Description>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
