// <auto-generated />
using System;
using Caravel.Worker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Caravel.Worker.Database.ResultMigrations
{
    [DbContext(typeof(ResultContext))]
    [Migration("20260928063709_CreateResults")]
    partial class CreateResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Caravel.Worker.ProcessedQuantity", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.HasIndex("TenantId");

                    b.ToTable("ProcessedQuantities");
                });
#pragma warning restore 612, 618
        }
    }
}
